### ISSUE TITLE
Pressing back button crashes the app when a webm is playing.

### ISSUE THREAD

**Issue by Rukkaitto** [Rukkaitto/mobichan#10]

**Comment by mitchross** [comment]
Which device / os ?

**Comment by Rukkaitto** [comment]
> Which device / os ?

Pixel 4a, Android 12

**Comment by mitchross** [comment]
I havent been able to reproduce yet. I have a pixel 4 xl with android 12 beta 2.

**Comment by Rukkaitto** [comment]
It hasn't happened in a while. Closing for now.
