### ISSUE TITLE
Threads don't load

### ISSUE THREAD

**Issue by lsvy97** [Rukkaitto/mobichan#115]
Just updated from 2.0.2 to 2.0.4 and threads don't load anymore.

**Comment by Rukkaitto** [comment]
> Just updated from 2.0.2 to 2.0.4 and threads don't load anymore. 

Have you tried clearing your cache?

**Comment by lsvy97** [comment]
> Have you tried clearing your cache?
Clearing cache didn't help, clearing data did it to me

**Comment by Rukkaitto** [comment]
Great, thanks for sharing.
Hope you're enjoying the app.
