### ISSUE TITLE
Ipad/iOS - No way to exit thread

### ISSUE THREAD

**Issue by mitchross** [Rukkaitto/mobichan#12]
Currently, there is no way to exit a thread on iOS. Looks like swipe gestures are not working. I might suggest changing hamburger button to a back button on a thread page maybe.

**Comment by Rukkaitto** [comment]
The issue is that I want to be able to have access to the side panel from threads as well.

**Comment by mitchross** [comment]
FWIW this is how the old 'mobichan' worked 

![IMG_1414](https://user-images.githubusercontent.com/6330506/124826774-3f231a00-df43-11eb-839d-ca24ece99753.JPG)
![IMG_1413](https://user-images.githubusercontent.com/6330506/124826777-40544700-df43-11eb-8883-96af23ef2f90.JPG)

**Comment by mitchross** [comment]
@Rukkaitto I figured it out. All you have to do is add 'import 'package:flutter/cupertino.dart';" to each page and swipe will work natively

**Comment by Rukkaitto** [comment]
If you want to make a PR I'll merge it

**Comment by mitchross** [comment]
I included it as part of https://github.com/Rukkaitto/mobichan/pull/14
