### ISSUE TITLE
Bloc/Cubit For State Management

### ISSUE THREAD

**Issue by mitchross** [Rukkaitto/mobichan#13]
You should consider using bloc or just cubit, for state management. The code will be much easier to maintain and you wont need to call setState all the time. 

Relative example 
https://bloclibrary.dev/#/flutterinfinitelisttutorial

**Comment by Rukkaitto** [comment]
I'll check it out, thanks. The code is getting a bit messy

**Comment by Rukkaitto** [comment]
I am currently working on migrating the app to a CLEAN architecture. I will use bloc in the presentation layer.

**Comment by mitchross** [comment]
Where are you at with CLEAN architecture? haven't seen movement on it.

Clean is a bit over kill, you can get away with half of the features of clean.

**Comment by Rukkaitto** [comment]
> Where are you at with CLEAN architecture? haven't seen movement on it.
> 
> Clean is a bit over kill, you can get away with half of the features of clean.

I'm a bit busy at the moment, but here's the rundown. Yes, CLEAN is way overkill and I gave up on switching to it, however I'm looking into some simple state management solutions to avoid passing callbacks all over the place.

**Comment by mitchross** [comment]
Try Cubit / Bloc. Thats what I use on all my projects. This is the best sample project to learn it https://github.com/felangel/fluttersaurus

**Comment by Rukkaitto** [comment]
I'll check it out, thanks.

**Comment by mitchross** [comment]
If you like written tutorials -> https://resocoder.com/2020/08/04/flutter-bloc-cubit-tutorial/

And once you do that try https://bloclibrary.dev/#/flutterweathertutorial

**Comment by mitchross** [comment]
@Rukkaitto do you want help with the initial bloc / cubit architecture?

**Comment by Rukkaitto** [comment]
> @Rukkaitto do you want help with the initial bloc / cubit architecture?

Sure, you can checkout feature/bloc-migration, I've started with boards.

Thanks a lot.

**Comment by mitchross** [comment]
Hey @Rukkaitto did you see https://github.com/Zchandev/iChan

It uses bloc, although Im not a fav of the architecture of bloc and you can simplify a ton of the code using cubits.

**Comment by Rukkaitto** [comment]
I'll check it out, thanks.

**Comment by Rukkaitto** [comment]
@mitchross I'm looking into the Stacked architecture with this plugin :

https://pub.dev/packages/stacked

What do you think?

**Comment by Rukkaitto** [comment]
Started with #29. I prefer it to Bloc so far.

**Comment by mitchross** [comment]
It's your app you should do what you feel best, I personally think bloc is the best. If you just use Cubit you can cut 75% of the boiler plate code with bloc.

MVVM is an outdated architecture for apps. The entire industry is moving to Unidirectional Data Flow or also known as one-way data flow. You see this with React Redux or React Context API.... Android and Ios are incorporating this natively to doing this pattern too. 

The benefit of one-way data flow is state is published out to subscribers, likely multiple areas of the app need the state change information. Lots of times with MVVM you have two way communication which quickly breaks down and causes all sorts of errors in your architecture. MVVM is easier to grasp initially, but for Flutter, which is tree-based, I think its the wrong pattern.

Which I first started Flutter, I did MVVM since that's was I was comfortable with at the time, I built this app https://github.com/mitchross/multi_camera_dashboard , infact I used no plugins or frameworks, just vanilla MVVM.


I would strongly suggest sticking with Bloc for community support and staying relevant in the industry. The issue you will find with Stacked is limited support.

End of the day, do what you want and feel comfortable with. If your goal is to learn and be relevant with the industry, stick with a UDF/Reactive framework, it will pay dividends in other tech stacks, especially React.

**Comment by Rukkaitto** [comment]
I'll give it a shot.

**Comment by mitchross** [comment]
Read through this 

https://resocoder.com/2020/08/04/flutter-bloc-cubit-tutorial/

Try
https://github.com/felangel/fluttersaurus
