### ISSUE TITLE
Webm view still crashes app when popped on Android

### ISSUE THREAD

**Issue by Rukkaitto** [Rukkaitto/mobichan#20]
How to reproduce:
- Open a webm
- Tap the back button in the top left or use the phone's navigation buttons/gestures to close the view.
- App will crash once and won't crash again for a while

Also, when the app is about to crash, you can hear the audio of the webm playing twice (might be a clue).

**Comment by mitchross** [comment]
I can fix this. I co-developed the re-write of VLC for flutter.

**Comment by Rukkaitto** [comment]
> I can fix this. I co-developed the re-write of VLC for flutter. 

That would be great 👍🏻

**Comment by mitchross** [comment]
https://github.com/Rukkaitto/mobichan/pull/26
