### ISSUE TITLE
Null Safety Build Issue

### ISSUE THREAD

**Issue by mitchross** [Rukkaitto/mobichan#8]
Can fix build issues with null safety with this fix

Remove
 # install_plugin: ^2.0.1

Add
  install_plugin: 
    git:
      url: https://github.com/mitchross/flutter_install_plugin.git
      
    I have a PR but doubt it will merge. https://github.com/hui-z/flutter_install_plugin/pull/54

**Comment by Rukkaitto** [comment]
Fixed in 7dd1706e863ad1e349136279a1a89b841f340fc4. Removed updates for now, as it is probably caused by Google Play Protect.
