### ISSUE TITLE
Gridview for tablet?

### ISSUE THREAD

**Issue by mitchross** [Rukkaitto/mobichan#9]
Thoughts on gridview ( catalog mode )  for tablet? 

<img width="482" alt="Screen Shot 2021-07-03 at 10 04 04 PM" src="https://user-images.githubusercontent.com/6330506/124370962-d722ba00-dc4a-11eb-938a-da931f8fec6e.png">

**Comment by Rukkaitto** [comment]
Looks great!

**Comment by Rukkaitto** [comment]
Commit 456de6091d8a90559124495784c19e6099d23f58 adds a gridview for all screens. Haven't tested it on larger screens, but it should work pretty well.

**Comment by mitchross** [comment]
Looks good on ipad. You might want to have a button for list/grid in the action bar. Some may prefer list over grid and vice versa.

**Comment by Rukkaitto** [comment]
Will probably make that a setting when the settings page is done.
